name 'workstation'
maintainer 'Chris Moultrie'
maintainer_email 'chri@moultrie.org'
license 'all_rights'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.2.1'
